source: "/Users/cat/.Trash/Downie"
target: "/Users/cat/Pictures/e1"
copy:
  to:
    delete: true

run:
  name: master1

master1:
  class: org.myrtle.citrus.Master1
  method:
    main: "main"

master2:
  class: org.myrtle.citrus.Master2
  method:
    init: "init"
    main: "main"
    close: "close"