test:
  context: "1"

ice:
  myrtle:
    # Myrtle-Canary 配置
    canary:
      # ice.myrtle.canary.AutoLog
      AutoLog:
        # 默认类查找深度
        classExplorationDepth: "2"
      # ice.myrtle.canary.ByteCache
      ByteCache:
        # 默认缓存文件配置
        createTempFile:
          # 默认文件名后缀
          suffixName: ".bin"
        # 默认Hex格式
        getHexs:
          # 默认Hex格式
          hexFormat: "%02X"
        # 默认hashCode乘数
        hashCode:
          # 默认hashCode乘数
          multiplier: "3"
      # ice.myrtle.canary.io.FindFilesOptions
      io:
        FindFilesOptions:
          # 默认排序方式
          sortBy: NAME
          # 默认文件名匹配模式
          patternExclusion: false
          # 默认是否递归
          subfolder: false
          # 默认是否包含隐藏文件
          includeHidden: false
          minSize: -1
          maxSize: -1
          modifiedAfter: 0
          modifiedBefore: -1

      # ice.myrtle.canary.io.IOKit
      IOKit:
        # 默认缓冲区大小
        defBufferSize: "1024"
      # ice.myrtle.canary.SystemKit
      SystemKit:
        # 默认编码
        encode: ${sys:file.encoding}
        # 默认路径分隔符
        pathSeparator: ${sys:path.separator}
        # 默认行分隔符
        lineSeparator: ${sys:line.separator}
        # 默认路径分隔符字符
        pathSeparatorChar: ${sys:path.separator}
        # 默认分隔符字符
        separator: ${sys:file.separator}
      # ice.myrtle.canary.VirtualFileSystem
      VirtualFileSystem:
        # 默认虚拟文件系统
        getRam:
          # 默认文件系统名称
          schemeName: "RamDisk"

os:
  shell: ${env:SHELL}
  path: ${env:PATH}
  user: ${env:USER}
  home: ${env:HOME}
  lang: ${env:LANG}